### ISSUE TITLE
 Which article is this project based on? Is there a link?

### ISSUE THREAD

**Issue by InsaneYoungStunner** [Scrawk/GPU-GEMS-3D-Fluid-Simulation#2]
Which article is this project based on? Is there a link?

**Comment by Scrawk** [comment]
https://developer.nvidia.com/gpugems/gpugems3/part-v-physics-simulation/chapter-30-real-time-simulation-and-rendering-3d-fluids

**Comment by InsaneYoungStunner** [comment]
Thanks~

Justin ***@***.***> 于2021年4月21日周三 上午2:25写道：
